export default function Mockingbird(){
    return(
        <div className="mockingbird">
            <p>To Kill a Mockingbird takes place in the fictional town of Maycomb, Alabama, during the Great Depression. The protagonist is Jean Louise (“Scout”) Finch, an intelligent though unconventional girl who ages from six to nine years old during the course of the novel. She is raised with her brother, Jeremy Atticus (“Jem”), by their widowed father, Atticus Finch. He is a prominent lawyer who encourages his children to be empathetic and just. He notably tells them that it is “a sin to kill a mockingbird,” alluding to the fact that the birds are innocent and harmless.

                When Tom Robinson, one of the town’s Black residents, is falsely accused of raping Mayella Ewell, a white woman, Atticus agrees to defend him despite threats from the community. At one point he faces a mob intent on lynching his client but refuses to abandon him. Scout unwittingly diffuses the situation. Although Atticus presents a defense that gives a more plausible interpretation of the evidence—that Mayella was attacked by her father, Bob Ewell—Tom is convicted, and he is later killed while trying to escape custody. A character compares his death to “the senseless slaughter of songbirds,” paralleling Atticus’s saying about the mockingbird.

T               he children, meanwhile, play out their own miniaturized drama of prejudice and superstition as they become interested in Arthur (“Boo”) Radley, a reclusive neighbour who is a local legend. They have their own ideas about him and cannot resist the allure of trespassing on the Radley property. Their speculations thrive on the dehumanization perpetuated by their elders. Atticus, however, reprimands them and tries to encourage a more sensitive attitude. Boo makes his presence felt indirectly through a series of benevolent acts, finally intervening when Bob Ewell attacks Jem and Scout. Boo kills Ewell, but Heck Tate, the sheriff, believes it is better to say that Ewell’s death occurred when he fell on his own knife, sparing the shy Boo from unwanted attention. Scout agrees, noting that to do otherwise would be “sort of like shootin’ a mockingbird.”</p>

            <h1>Analysis, adaptations, and Go Set a Watchman</h1>
            <p>
            To Kill a Mockingbird is both a young girl’s coming-of-age story and a darker drama about the roots and consequences of racism and prejudice, probing how good and evil can coexist within a single community or individual. Scout’s moral education is twofold: to resist abusing others with unfounded negativity but also to persevere when these values are inevitably, and sometimes violently, subverted. Criticism of the novel’s tendency to sermonize has been matched by praise of its insight and stylistic effectiveness.

Lee reportedly based the character of Atticus Finch on her father, Amasa Coleman Lee, a compassionate and dedicated lawyer and newspaper editor. The plot of To Kill a Mockingbird was inspired in part by his unsuccessful youthful defense in 1919 of two African American men convicted of murder, the only criminal case he ever took.

One character from the novel, Charles Baker (“Dill”) Harris, is based on Truman Capote, Lee’s friend since childhood and next-door neighbour in Monroeville, Alabama. Lee served as the basis of the tomboy Idabel Thompkins in Capote’s first novel, Other Voices, Other Rooms (1948). In the winter of 1959–60, just before the release of To Kill a Mockingbird, Lee journeyed to Kansas with Capote and helped him in the research for his “nonfiction novel” In Cold Blood, about the murder of four members of the Clutter family. After the phenomenal success that followed the publication of To Kill a Mockingbird and the lack of further novels from Lee, some suspected that Capote was the actual author of Lee’s work, a rumour put to rest when, in 2006, a 1959 letter from Capote to his aunt was found, stating that he had read and liked the draft of To Kill a Mockingbird that Lee had shown him but making no mention of any role in writing it.
            </p>

            <p>The novel inspired adaptations, the most notable of which was the classic 1962 film starring Gregory Peck as Atticus. His Academy Award-winning performance became an enduring part of cinema history. (Robert Duvall made his film debut as Boo Radley.) Aaron Sorkin adapted the novel into a Broadway play that debuted in 2018. (Lee’s estate sued over Sorkin’s adaptation in which Atticus rather than Scout was the main character, but the dispute was resolved before the play opened.)</p>
       
            <p>In 2015 Lee released a second novel: Go Set a Watchman, written just before To Kill a Mockingbird but set 20 years later featuring Scout as a grown woman based in New York City who returns to her Alabama childhood home to visit her father. Although some claimed Go Set a Watchman is an earlier draft of To Kill a Mockingbird, it was actually Lee’s first novel, completed in 1957. Lee then began a second novel incorporating short stories based on her childhood. Lee was encouraged by her agent Maurice Crain to finish the second novel and not try to merge the two books. However, after the enormous success of To Kill a Mockingbird, Lee set Go Set a Watchman aside, and the completed manuscript of that novel languished in a safe-deposit box in Monroeville for decades. Go Set a Watchman excited controversy because it depicts Atticus as an ardent segregationist whose views horrify Scout, who has to reconcile Atticus’s racist attitudes with the kindly and loving father of her childhood memories.</p>
        </div>
    )
}